automatic amend-commit in post-commit hook

diff --git a/tools/git-hooks/post-commit b/tools/git-hooks/post-commit
--- a/tools/git-hooks/post-commit
+++ b/tools/git-hooks/post-commit
@@ -7,6 +7,11 @@ root="$(git rev-parse --show-toplevel)"
 
 echo "Post-Commit Hook: add automatically changed files ..."
 
+function deleteFile()
+{
+    rm "${root}/.pre-commit-changed"
+}
+
 function addFile()
 {
     file="$1"
@@ -15,17 +20,18 @@ function addFile()
 }
 export -f addFile
 
-cat "${root}/.pre-commit-changed" | xargs -n 1 -0 -I {} bash -c 'addFile "${@}"' _ {}
-rm "${root}/.pre-commit-changed"
+cat "${root}/.pre-commit-changed" | xargs -n 1 -0 -I {} bash -c 'addFile "${@}"' _ {} || (deleteFile; echo "Error!"; exit 0)
+
+deleteFile
 
 # Show the status
 git status
 
 # Allows us to read user input below, assigns stdin to keyboard
-exec < /dev/tty
-read -p "Post-Commit Hook: Do you want to auto amend-commit the changed files? (Y/n) (default: n) " yn
+# exec < /dev/tty
+# read -p "Post-Commit Hook: Do you want to auto amend-commit the changed files? (Y/n) (default: n) " yn
 if [ "$yn" = "" ]; then
-    yn='n'
+    yn='Y'
 fi
 case $yn in
     [Y] ) git commit --amend -C HEAD --no-verify
