Response and Request concepts improved

diff --git a/tools/git-hooks/autoformat/html b/tools/git-hooks/autoformat/html
--- a/tools/git-hooks/autoformat/html
+++ b/tools/git-hooks/autoformat/html
@@ -2,6 +2,8 @@
 # format all XML (HTML) files in the repository
 # to use this tool install: npm install -g xmllint
 
+set -e
+
 REPO_DIR="$(git rev-parse --show-toplevel)"
 owndir="$(cd "$(dirname "$0")"; pwd -P)"
 
@@ -9,8 +11,7 @@ function formatFile() {
     file=$1
     echo "formatting html file: $file"
     echo "file: $file" >> tidy.log
-    tidy -config "$2" -m $file 2>>tidy.log #|| echo 'fatal: `tidy` failed for:' "$file" >&2 && exit 1
-    # ignore tidy errors!
+    tidy -config "$2" -m $file 2>>tidy.log #|| (echo 'fatal: `tidy` failed for:' "$file" >&2 ; exit 1)
 }
 export -f formatFile
 
diff --git a/tools/git-hooks/autoformat/xml b/tools/git-hooks/autoformat/xml
--- a/tools/git-hooks/autoformat/xml
+++ b/tools/git-hooks/autoformat/xml
@@ -2,15 +2,16 @@
 # format all XML (HTML) files in the repository
 # to use this tool install: npm install -g xmllint
 
+set -e
+
 REPO_DIR="$(git rev-parse --show-toplevel)"
 owndir="$(cd "$(dirname "$0")"; pwd -P)"
 
 function formatFile() {
     file=$1
-    echo "formatting xml file: $file"
-    fileTmp=$(mktemp)
-    tidy -config $2 -xml -m $file 2>/dev/null || (echo 'fatal: `tidy` failed for:' "$file" >&2 ; exit 1)
-    mv $fileTmp $file
+    echo "formatting html file: $file"
+    echo "file: $file" >> tidy.log
+    tidy -config "$2" -xml -m $file 2>/dev/null || (echo 'fatal: `tidy` failed for:' "$file" >&2 ; exit 1)
 }
 export -f formatFile
 
